var grid1TableConf = [
  {
    title: "enryID",
    field: "EnryID",
    headerHozAlign: "center",
    hozAlign: "center",
    visible: false,
    headerSort: false,
  }, {
    title: "id",
    field: "id",
    headerHozAlign: "center",
    hozAlign: "center",
    visible: false,
    headerSort: false,
  },
  {
    title: "进货单号",
    field: "code",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 180,
    headerSort: false,
  },
  {
    title: "进货日期",
    field: "voucherDate",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 120,
    headerSort: false,
  },
  {
    title: "供应商",
    field: "cVenName",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 250,
    headerSort: false,
  },
  {
    title: "存货编码",
    field: "cInvCode",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "存货名称",
    field: "cInvName",
    headerHozAlign: "center",
    hozAlign: "center",
    headerSort: false,
    width: 200,
  },
  {
    title: "规格型号",
    field: "cInvStd",
    headerHozAlign: "center",
    hozAlign: "center",
    headerSort: false,
    width: 250,
  },
  {
    title: "单位",
    field: "cUnit",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 120,
    headerSort: false,
  },
  {
    title: "数量",
    field: "iQuantity",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 120,
    headerSort: false
  },
  {
    title: "包装数量",
    field: "iPackQuantity",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 120,
    headerSort: false,
    editor: "number",
    editorParams: {
      min: 1,
      step: 1,
    },
  },
  {
    title: "批号",
    field: "cBatch",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 120,
    headerSort: false,
    editor: 'input'
  },
];

var grid2TableConf = [
  {
    title: "id",
    field: "id",
    headerHozAlign: "center",
    hozAlign: "center",
    visible: false,
    headerSort: false,
  },
  {
    title: "生成时间",
    field: "FDate",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "供应商",
    field: "FVenName",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 250,
    headerSort: false,
  },
  {
    title: "存货编码",
    field: "FInvCode",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "存货名称",
    field: "FInvName",
    headerHozAlign: "center",
    hozAlign: "center",
    headerSort: false,
    width: 150,
  },
  {
    title: "规格型号",
    field: "FInvStd",
    headerHozAlign: "center",
    hozAlign: "center",
    headerSort: false,
    width: 250,
  },
  {
    title: "单位",
    field: "FComUnitName",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 120,
    headerSort: false,
  },
  {
    title: "数量",
    field: "FQty",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 120,
    headerSort: false,
    editor: "number",
    editorParams: {
      min: 0,
    },
  },
  {
    title: "批号",
    field: "FBatch",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 120,
    headerSort: false,
  },
  {
    title: "条码",
    field: "FBarcode",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 320,
    headerSort: false,
  },
]; 
